### ISSUE TITLE
GB dynamic image link source received a Lighthouse accessibility warning

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#751] opened 2022-10-30 21:53 UTC
When a GB dynamic image link is set from the `Link source`, the link is flagged by Lighthouse as a link that does not have a discernible name.
https://i.imgur.com/zUof5DW.png

**Comment by diggeddy** [comment] 2023-10-17 21:01
Closed as duplicate of:
https://github.com/tomusborne/generateblocks/issues/678

**Closed by diggeddy** 2023-10-17 21:01 UTC
Labels: triage
