### ISSUE TITLE
GB 1.7 beta 1: Editor bug with inline and inline-flex display

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generateblocks#897] opened 2023-01-29 19:54 UTC
Similar to this bug here: https://github.com/tomusborne/generateblocks/issues/896

See this video as well: https://www.screencast.com/t/iOSYRG9K7sA7

**Comment by tomusborne** [comment] 2023-01-29 20:01
duplicate of #878

**Closed by tomusborne** 2023-01-29 20:01 UTC
Labels: triage
