### ISSUE TITLE
Feature: Global style autocomplete to search for any match, not just "string starts with"

### ISSUE THREAD

**Issue by frzsombor** [tomusborne/generateblocks#1249] opened 2024-06-15 21:04 UTC
### Description
I think it would be really helpful if the autocomplete of global style class add/search box would match any part of the string, as - for conventional reasons - I name the styles as actual class names. I have classes like `bg-gradient-colorname` and many others, and it would be better to be able to start typing "gradi" and I would see all the gradient classes.

_Edit: By the way, this works flawlessly when I'm creating a new style and select "clone". In that input field, the search works with match anywhere in the strings._

![image](https://github.com/tomusborne/generateblocks/assets/7306657/f63324ed-4862-4522-899e-b2687f3a881d)
![image](https://github.com/tomusborne/generateblocks/assets/7306657/17eed197-d1d0-4a48-852c-959654fbdd12)

**Comment by iansvo** [comment] 2024-08-13 19:21
Thanks for the report on this. The reason this was happening is because the autocomplete in question was adding the period to the query if it wasn't already there, which isn't exactly what we want for a fuzzy match. This should be fixed next release.

**Comment by iansvo** [comment] 2024-11-29 17:23
Confirmed this is fixed in 2.0.

**Closed by iansvo** 2024-11-29 17:23 UTC
Labels: bug
