### ISSUE TITLE
Responsive switcher buggy - switching itself back to desktop after selecting mobile & overwriting desktop values

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generateblocks#950] opened 2023-03-16 18:03 UTC
I've noticed the responsive switcher options have become a little bit buggy for me since the 1.7 release. 

Not everytime, but it has happened frequently enough for me to notice that switching device previews, normally from desktop down to mobile, the toggle will switch back to desktop wihtout you knowing as the preview will still appear to be in mobile view. 

When this happens the changes apply to desktop even though it looks like you are still editing mobile overwriting any desktop values. Not sure if it is browser specific at the moment, but if it helps I mostly use Firefox when editing.

Thanks

**Comment by JeanPaiva** [comment] 2023-03-16 18:21
Thanks, we will look into that to fix it for the next version.

**Comment by tomusborne** [comment] 2023-05-18 14:31
I'm not able to reproduce this. @eastriverstudio does this happen to you frequently?

**Comment by tomusborne** [comment] 2023-05-22 15:19
Thanks! I'll close this for now but feel free to re-open if you notice it again.

**Closed by tomusborne** 2023-05-22 15:19 UTC
Labels: bug
