### ISSUE TITLE
Query block - Container dynamic background image not visible in the front end

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generateblocks#304] opened 2022-04-20 14:37 UTC
When setting a dynamic container featured image inside a query loop block:
1. The image displayed in the backend for all posts is the image of the last post in the query.
2. Images are not displayed in the front end.
3. When setting a dynamic link to a single post, only the first two links work.

**Comment by tomusborne** [comment] 2022-04-20 22:16
I'm not able to reproduce 1 or 2, but I am seeing 3 when using `query-loop-block` with the current version of GBP. It should be fixed if you use the `release/1.2.0` branch: https://github.com/tomusborne/generateblocks-pro/tree/release/1.2.0

**Closed** 2022-04-20 23:24 UTC
Labels: type: bug, block: Query loop
